In [ ]:
import pandas as pd

# Students DataFrame
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}

students_df = pd.DataFrame(students_data)
print("student df created")
print (students_df)


# Enrollments DataFrame
enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}

enrollments_df = pd.DataFrame(enrollments_data)
print("Enrollment details created")
print(enrollments_df)

# Scores DataFrame
scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}

scores_df = pd.DataFrame(scores_data)
print("score details created")
print(scores_df)

student df created
   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com       None
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi
Enrollment details created
   student_id       course_name enrollment_date
0         101            Python      2024-01-15
1         102      Data Science      2024-01-20
2         103            Python      2024-02-01
3         105  Machine Learning      2024-02-10
4         108                AI      2024-02-15
5         109            Python      2024-03-01
score details created
   student_id  exam_score
0         101          85
1         102          92
2         104          78
3         105          88
4         106          95


create and manage three separate DataFrames: students_df, enrollments_df, and scores_df. It first imports pandas as pd. Then, it defines three dictionaries (students_data, enrollments_data, and scores_data) which hold the raw data. Each dictionary is then converted into a pandas.DataFrame. Finally, it prints the students_df

In [ ]:
null_count = students_df.isnull().sum()

# Null percentage
null_percentage = (students_df.isnull().sum() / len(students_df)) * 100

# Combine both
null_summary = pd.DataFrame({
    'Null Count': null_count,
    'Null Percentage': null_percentage
})

print(null_summary)

            Null Count  Null Percentage
student_id           0         0.000000
name                 1        14.285714
email                1        14.285714
city                 1        14.285714


 displays a summary of null (missing) values in the students_df DataFrame. First, it determines the count of null values for each column and stores it in null_count. it combines both the null counts and null percentages into a new DataFrame called null_summary and prints this summary to the console, providing a clear overview of missing data in students_df.

In [ ]:
students_df['city'] = students_df['city'].fillna('Unknown')
print(students_df)

   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com    Unknown
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi


fills any missing values (represented as None or NaN) in the 'city' column of the students_df DataFrame with the string 'Unknown'.

In [ ]:
students_df = students_df.dropna(subset=['name'])
print(students_df)

   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi


The dropna() method is used for this, and subset=['name'] specifies that only the 'name' column should be checked for null values. After the rows are dropped, the modified students_df is printed to the console.

In [ ]:
print("\nCleaned Students DataFrame:")
print(students_df)


Cleaned Students DataFrame:
   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi


This code first prints a descriptive string, 'Cleaned Students DataFrame:', to the console. Immediately after, it prints the current state of the students_df DataFrame.

In [ ]:
inner_df = pd.merge(students_df, enrollments_df,
                    on='student_id',
                    how='inner')

print(inner_df)
print("Total rows:", len(inner_df))

   student_id   name            email     city       course_name  \
0         101  Alice  alice@email.com   Mumbai            Python   
1         102    Bob    bob@email.com    Delhi      Data Science   
2         105   Emma   emma@email.com  Unknown  Machine Learning   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-10  
Total rows: 3


performs an inner merge operation between the students_df and enrollments_df DataFrames. It uses the student_id column as the key for merging, meaning it will combine rows where the student_id is present in both DataFrames.

Common student_ids in both tables:

101

102

105

👉 Total = 3 students

Which students are excluded and why?

From students table, excluded IDs:

104

106

107

👉 They are excluded because they do not exist in enrollments table.

In [ ]:
left_df = pd.merge(students_df, enrollments_df,
                   on='student_id',
                   how='left')

print(left_df)
print("Total rows:", len(left_df))

   student_id   name            email     city       course_name  \
0         101  Alice  alice@email.com   Mumbai            Python   
1         102    Bob    bob@email.com    Delhi      Data Science   
2         104  David             None   Mumbai               NaN   
3         105   Emma   emma@email.com  Unknown  Machine Learning   
4         106  Frank  frank@email.com  Chennai               NaN   
5         107  Grace  grace@email.com    Delhi               NaN   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2             NaN  
3      2024-02-10  
4             NaN  
5             NaN  
Total rows: 6


How many total rows?

Left join keeps all students:

👉 Total rows = 6

✔ Which students have null course_name and why?

Students:

104

106

107

👉 Because they have no matching enrollment record.

In [ ]:
right_df = pd.merge(students_df, enrollments_df,
                    on='student_id',
                    how='right')

print(right_df)
print("Total rows:", len(right_df))

   student_id   name            email     city       course_name  \
0         101  Alice  alice@email.com   Mumbai            Python   
1         102    Bob    bob@email.com    Delhi      Data Science   
2         103    NaN              NaN      NaN            Python   
3         105   Emma   emma@email.com  Unknown  Machine Learning   
4         108    NaN              NaN      NaN                AI   
5         109    NaN              NaN      NaN            Python   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3      2024-02-10  
4      2024-02-15  
5      2024-03-01  
Total rows: 6


✔ How many total rows?

Right join keeps all enrollments:

👉 Total rows = 6

✔ Which student_ids appear but don’t have names?

From enrollments:

103

108

109

👉 These IDs exist in enrollments but:

103 was dropped earlier (name was missing)

108 and 109 don’t exist in students table

So their name column will be NaN.

In [ ]:
#Full outer join
outer_df = pd.merge(students_df, enrollments_df,
                    on='student_id',
                    how='outer')

print(outer_df)
print("Total rows:", len(outer_df))

   student_id   name            email     city       course_name  \
0         101  Alice  alice@email.com   Mumbai            Python   
1         102    Bob    bob@email.com    Delhi      Data Science   
2         103    NaN              NaN      NaN            Python   
3         104  David             None   Mumbai               NaN   
4         105   Emma   emma@email.com  Unknown  Machine Learning   
5         106  Frank  frank@email.com  Chennai               NaN   
6         107  Grace  grace@email.com    Delhi               NaN   
7         108    NaN              NaN      NaN                AI   
8         109    NaN              NaN      NaN            Python   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3             NaN  
4      2024-02-10  
5             NaN  
6             NaN  
7      2024-02-15  
8      2024-03-01  
Total rows: 9


How many total rows?

Unique IDs from both tables:

101,102,104,105,106,107,103,108,109

👉 Total = 9 rows

In [ ]:
#Rows where name is null OR course_name is null
problem_rows = outer_df[
    outer_df['name'].isnull() | outer_df['course_name'].isnull()
]

print(problem_rows)

   student_id   name            email     city course_name enrollment_date
2         103    NaN              NaN      NaN      Python      2024-02-01
3         104  David             None   Mumbai         NaN             NaN
5         106  Frank  frank@email.com  Chennai         NaN             NaN
6         107  Grace  grace@email.com    Delhi         NaN             NaN
7         108    NaN              NaN      NaN          AI      2024-02-15
8         109    NaN              NaN      NaN      Python      2024-03-01


Students without enrollments (104,106,107)

Enrollments without student info (103,108,109)

In [ ]:
#Outer Join with Indicator
outer_indicator_df = pd.merge(
    students_df, enrollments_df,
    on='student_id',
    how='outer',
    indicator=True
)

print(outer_indicator_df['_merge'].value_counts())

_merge
left_only     3
right_only    3
both          3
Name: count, dtype: int64


print(outer_indicator_df['_merge'].value_counts()) displays the count of rows for each of these categories, giving you a clear summary of how many students are only in the student list, only in enrollments, or in both.




In [ ]:
score_dict = dict(zip(scores_df['student_id'], scores_df['exam_score']))
print(score_dict)

{101: 85, 102: 92, 104: 78, 105: 88, 106: 95}


e_dict.

    scores_df['student_id'] selects the 'student_id' column from the scores_df DataFrame.
    scores_df['exam_score'] selects the 'exam_score' column from the scores_df DataFrame.
    The zip() function pairs up corresponding elements from these two Series (the student IDs and their respective exam scores).
    Finally, dict() converts these paired elements into a dictionary where each student_id is a key and its exam_score is the corresponding value.


In [ ]:
students_df['exam_score'] = students_df['student_id'].map(score_dict)

print(students_df)

   student_id   name            email     city  exam_score
0         101  Alice  alice@email.com   Mumbai        85.0
1         102    Bob    bob@email.com    Delhi        92.0
3         104  David             None   Mumbai        78.0
4         105   Emma   emma@email.com  Unknown        88.0
5         106  Frank  frank@email.com  Chennai        95.0
6         107  Grace  grace@email.com    Delhi         NaN


It uses the map() method on the student_id column of students_df. The score_dict (which you created in the previous step, mapping student_id to exam_score) is passed to map().

In [ ]:
merged_scores = pd.merge(
    students_df.drop(columns=['exam_score']),  # remove previous column for clean test
    scores_df,
    on='student_id',
    how='left'
)
print(merged_scores)

   student_id   name            email     city  exam_score
0         101  Alice  alice@email.com   Mumbai        85.0
1         102    Bob    bob@email.com    Delhi        92.0
2         104  David             None   Mumbai        78.0
3         105   Emma   emma@email.com  Unknown        88.0
4         106  Frank  frank@email.com  Chennai        95.0
5         107  Grace  grace@email.com    Delhi         NaN


The result, merged_scores, will contain all students from the (cleaned) students_df along with their exam_score from scores_df, with NaN for students who don't have a score.

In [ ]:
#all in one:final program
import pandas as pd

# ===============================
# === TASK 1: Data Preparation ===
# ===============================

print("=== TASK 1: Data Preparation ===\n")

# Create Students DataFrame
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None,
              'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}

students_df = pd.DataFrame(students_data)

print("Original Students DataFrame:")
print(students_df)
print()

# Null Value Analysis
print("Null Value Analysis:")
for col in students_df.columns:
    null_count = students_df[col].isnull().sum()
    null_percent = (null_count / len(students_df)) * 100
    print(f"Column: {col}, Nulls: {null_count} ({null_percent:.2f}%)")

# Cleaning
students_df['city'] = students_df['city'].fillna('Unknown')
students_df = students_df.dropna(subset=['name'])

print("\nCleaned Students DataFrame ({} rows):".format(len(students_df)))
print(students_df)
print()


# ===============================
# === TASK 2: Join Operations ===
# ===============================

print("=== TASK 2: Join Operations ===\n")

# Create Enrollments DataFrame
enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python',
                    'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01',
                        '2024-02-10', '2024-02-15', '2024-03-01']
}

enrollments_df = pd.DataFrame(enrollments_data)

# -------- INNER JOIN --------
inner_df = pd.merge(students_df, enrollments_df,
                    on='student_id', how='inner')

print("Inner Join Result ({} rows):".format(len(inner_df)))
print(inner_df[['student_id', 'name', 'course_name', 'enrollment_date']])

excluded = list(set(students_df['student_id']) -
                set(inner_df['student_id']))

print(f"Excluded students: {excluded} - Not in enrollments table\n")


# -------- LEFT JOIN --------
left_df = pd.merge(students_df, enrollments_df,
                   on='student_id', how='left')

print("Left Join Result ({} rows):".format(len(left_df)))
print(left_df[['student_id', 'name', 'course_name', 'enrollment_date']])

null_courses = left_df[left_df['course_name'].isnull()]['student_id'].tolist()
print(f"Students with null course_name: {null_courses}\n")


# -------- RIGHT JOIN --------
right_df = pd.merge(students_df, enrollments_df,
                    on='student_id', how='right')

print("Right Join Result ({} rows):".format(len(right_df)))
print(right_df[['student_id', 'name', 'course_name', 'enrollment_date']])

no_names = right_df[right_df['name'].isnull()]['student_id'].tolist()
print(f"Student_ids without names: {no_names}\n")


# -------- OUTER JOIN --------
outer_df = pd.merge(students_df, enrollments_df,
                    on='student_id', how='outer')

print("Outer Join Result ({} rows):".format(len(outer_df)))
print(outer_df[['student_id', 'name', 'course_name', 'enrollment_date']])

problem_rows = outer_df[
    outer_df['name'].isnull() | outer_df['course_name'].isnull()
]

print("\nRows with missing name OR course_name:")
print(problem_rows[['student_id', 'name', 'course_name']])
print()


# -------- OUTER JOIN WITH INDICATOR --------
outer_indicator = pd.merge(
    students_df, enrollments_df,
    on='student_id',
    how='outer',
    indicator=True
)

print("Merge Source Distribution:")
print(outer_indicator['_merge'].value_counts())
print()


# ===============================
# === TASK 3: Lookup & Automation ===
# ===============================

print("=== TASK 3: Lookup and Automation ===\n")

# Create Scores DataFrame
scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}

scores_df = pd.DataFrame(scores_data)

# Lookup using map
score_dict = dict(zip(scores_df['student_id'], scores_df['exam_score']))
students_df['exam_score'] = students_df['student_id'].map(score_dict)

print("Lookup Operation Result:")
print(students_df[['student_id', 'name', 'exam_score']])
print()


# ===============================
# Automation Function
# ===============================

def auto_merge(df1, df2, join_type, key_column):
    merged_df = pd.merge(df1, df2,
                         on=key_column,
                         how=join_type)

    return {
        'result_df': merged_df,
        'row_count': len(merged_df),
        'join_type': join_type
    }

# Test 1 - Inner Join
result_inner = auto_merge(students_df, enrollments_df, 'inner', 'student_id')

print("Automation Function Test:")
print("Join Type:", result_inner['join_type'])
print("Rows in Result:", result_inner['row_count'])
print("Result Preview:")
print(result_inner['result_df'][['student_id','name','course_name']].head())
print()

# Test 2 - Left Join
result_left = auto_merge(students_df, enrollments_df, 'left', 'student_id')

print("Join Type:", result_left['join_type'])
print("Rows in Result:", result_left['row_count'])
print("Result Preview:")
print(result_left['result_df'][['student_id','name','course_name']].head())

=== TASK 1: Data Preparation ===

Original Students DataFrame:
   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com       None
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi

Null Value Analysis:
Column: student_id, Nulls: 0 (0.00%)
Column: name, Nulls: 1 (14.29%)
Column: email, Nulls: 1 (14.29%)
Column: city, Nulls: 1 (14.29%)

Cleaned Students DataFrame (6 rows):
   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi

=== T