In [ ]:
import pandas as pd
import numpy as np

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)
print(df)
#df.info()
#print(df)

    patient_id      age weight  blood_pressure  medication insurance_provider
0          101       25     70           120.0     Aspirin         Blue Cross
1          102       34     65           130.0   Metformin              Aetna
2          103     None     80             NaN  Lisinopril              Cigna
3          104       45   None           140.0        None       UnitedHealth
4          105       29     75           125.0     Aspirin               None
5          106     None   None             NaN   Metformin         Blue Cross
6          107       38     68           135.0  Lisinopril              Aetna
7          108       52     90             NaN     Aspirin              Cigna
8          109       27     72           118.0        None       UnitedHealth
9          110       41     85           145.0   Metformin         Blue Cross
10         111       33     78           128.0  Lisinopril              Aetna
11         112  unknown   None             NaN     Aspirin      

In [ ]:
#df = pd.DataFrame(data)
df.info()
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   patient_id          20 non-null     int64  
 1   age                 17 non-null     object 
 2   weight              16 non-null     object 
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object 
 5   insurance_provider  17 non-null     object 
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB
    patient_id      age weight  blood_pressure  medication insurance_provider
0          101       25     70           120.0     Aspirin         Blue Cross
1          102       34     65           130.0   Metformin              Aetna
2          103     None     80             NaN  Lisinopril              Cigna
3          104       45   None           140.0        None       UnitedHealth
4          105       29     75           125.0     Asp

provides a concise summary of the DataFrame. It prints information about the DataFrame including the index dtype and column dtypes, non-null values, and memory usage

In [12]:
df.isnull().sum()
#(df.isnull().sum() / len(df)) * 100

,0
age,4


used to count the number of missing (null or NaN) values in each column of your DataFrame df. First, df.isnull() returns a boolean DataFrame of the same shape as df, indicating True where a value is null and False otherwise.

In [13]:
(df.isnull().sum() / len(df)) * 100





,0
age,20.0


This code calculates the percentage of missing values for each column in the DataFrame df.This count is divided by len(df), which is the total number of rows in the DataFrame, to get the proportion of missing values.

In [ ]:
#df.duplicated().sum()
df.duplicated(subset='patient_id').sum()

np.int64(2)

checks for duplicate patient_id values across the DataFrame, returning True for any row where the patient_id has appeared previously. id value 101 & 107

In [ ]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')
print(df)

    patient_id   age weight  blood_pressure  medication insurance_provider
0          101  25.0     70           120.0     Aspirin         Blue Cross
1          102  34.0     65           130.0   Metformin              Aetna
2          103   NaN     80             NaN  Lisinopril              Cigna
3          104  45.0   None           140.0        None       UnitedHealth
4          105  29.0     75           125.0     Aspirin               None
5          106   NaN   None             NaN   Metformin         Blue Cross
6          107  38.0     68           135.0  Lisinopril              Aetna
7          108  52.0     90             NaN     Aspirin              Cigna
8          109  27.0     72           118.0        None       UnitedHealth
9          110  41.0     85           145.0   Metformin         Blue Cross
10         111  33.0     78           128.0  Lisinopril              Aetna
11         112   NaN   None             NaN     Aspirin               None
12         113  48.0     

converts the 'age' column of your DataFrame df to a numeric data type. The errors='coerce' argument is important here: if any value in the 'age' column cannot be converted to a number (like 'unknown' or None), it will be replaced with NaN (Not a Number)

In [ ]:
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')
print(df)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103   NaN    80.0             NaN  Lisinopril              Cigna
3          104  45.0     NaN           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin               None
5          106   NaN     NaN             NaN   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0             NaN     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112   NaN     NaN             NaN     Aspirin               None
12         1

 converts the 'weight' column of your DataFrame df to a numeric data type. Similar to what was done for the 'age' column, the errors='coerce' argument ensures that any non-numeric values (like 'N/A' or None) in the 'weight' column are replaced with NaN (Not a Number), preventing errors during conversion.

In [ ]:
# Missing values before conversion
missing_before = df[['age', 'weight']].isnull().sum()

# (Re-run conversion here if needed)
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')

# Missing values after conversion
missing_after = df[['age', 'weight']].isnull().sum()

# Newly created missing values
new_missing = missing_after - missing_before

print("Missing Before:\n", missing_before)
print("\nMissing After:\n", missing_after)
print("\nNew Missing Created:\n", new_missing)

Missing Before:
 age       4
weight    5
dtype: int64

Missing After:
 age       4
weight    5
dtype: int64

New Missing Created:
 age       0
weight    0
dtype: int64


the 'age' and 'weight' columns into missing_before. It then re-runs the conversion of both 'age' and 'weight' columns to numeric types, using pd.to_numeric with errors='coerce', which replaces any non-convertible values with NaN.

In [20]:
import pandas as pd

df = pd.DataFrame({
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44']
})

df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = df['age'].fillna(df['age'].median())

print(df)

     age
0   25.0
1   34.0
2   34.5
3   45.0
4   29.0
5   34.5
6   38.0
7   52.0
8   27.0
9   41.0
10  33.0
11  34.5
12  48.0
13  26.0
14  35.0
15  25.0
16  38.0
17  31.0
18  34.5
19  44.0


creates a DataFrame with an 'age' column containing various data types, including strings and missing values. It then converts the 'age' column to a numeric type, replacing any non-numeric entries with NaN.

In [24]:

# Missing values before conversion
missing_before = df['age'].isnull().sum()

# Convert to numeric
df['age'] = pd.to_numeric(df['age'], errors='coerce')

# Missing values after conversion
missing_after = df['age'].isnull().sum()

# New missing values created
new_missing = missing_after - missing_before

print("New missing values created:", new_missing)


missing_before = df['age'].isnull().sum()

df['age'] = pd.to_numeric(df['age'], errors='coerce')

missing_after = df['age'].isnull().sum()
print("New missing values:", missing_after - missing_before)

#df['insurance_provider'] = df['insurance_provider'].astype('category')

#print(df.dtypes)



New missing values created: 0
New missing values: 0


This code block first converts the 'insurance_provider' column of your DataFrame df to a categorical data type. This is often done for columns that have a limited number of unique values, as it can save memory and speed up certain operations.

In [34]:
import pandas as pd
import numpy as np

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)

df['insurance_provider'] = df['insurance_provider'].astype('category')

df.columns = df.columns.str.strip().str.replace(' ', '_')
print(df.columns)
df.dtypes
df.columns = df.columns.str.strip()
print(df.dtypes)






Index(['patient_id', 'age', 'weight', 'blood_pressure', 'medication',
       'insurance_provider'],
      dtype='object')
patient_id               int64
age                     object
weight                  object
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object


 it defines a dictionary named data containing various patient information, which is then used to create a pandas DataFrame called df. Next, it converts the 'insurance_provider' column to a categorical data type, which is efficient for columns with a limited number of unique values. After that, it standardizes all column names by removing leading/trailing spaces and replacing internal spaces with underscores.

It calculates the median of the existing 'age' values and then uses this median to fill in any NaN (missing) values in that column

In [36]:
#task3
#age: Fill with median using fillna(df['age'].median())
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'].fillna(df['age'].median(), inplace=True)

print(df)

    patient_id   age weight  blood_pressure  medication insurance_provider
0          101  25.0     70           120.0     Aspirin         Blue Cross
1          102  34.0     65           130.0   Metformin              Aetna
2          103  34.5     80             NaN  Lisinopril              Cigna
3          104  45.0   None           140.0        None       UnitedHealth
4          105  29.0     75           125.0     Aspirin                NaN
5          106  34.5   None             NaN   Metformin         Blue Cross
6          107  38.0     68           135.0  Lisinopril              Aetna
7          108  52.0     90             NaN     Aspirin              Cigna
8          109  27.0     72           118.0        None       UnitedHealth
9          110  41.0     85           145.0   Metformin         Blue Cross
10         111  33.0     78           128.0  Lisinopril              Aetna
11         112  34.5   None             NaN     Aspirin                NaN
12         113  48.0     

/tmp/ipykernel_1039/918708584.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)


This code block first converts the 'age' column of your DataFrame df to a numeric data type, using errors='coerce' to replace any non-numeric entries (like 'unknown' or None) with NaN (Not a Number). Then, it calculates the median of the 'age' column and uses this median value to fill in all the NaN entries in that column.

In [40]:
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')
df['weight'] = df['weight'].fillna(df['weight'].median())
df['weight'].fillna(df['weight'].median(), inplace=True)
print(df)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0             NaN  Lisinopril              Cigna
3          104  45.0    74.0           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106  34.5    74.0             NaN   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0             NaN     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5    74.0             NaN     Aspirin                NaN
12         1

/tmp/ipykernel_1039/3065347920.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weight'].fillna(df['weight'].median(), inplace=True)


handle missing values in weight column. It calculates the median of the existing 'weight' values and then uses this median to fill in any NaN (missing) values in that column. The inplace=True argument means that the DataFrame df is modified directly, without needing to reassign the column

In [43]:

df['blood_pressure'] = pd.to_numeric(df['blood_pressure'], errors='coerce')
df['blood_pressure'] = df['blood_pressure'].fillna(df['weight'].median())
df['blood_pressure'].fillna(df['blood_pressure'].median(), inplace=True)
print(df)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0         NaN         Blue Cross
1          102  34.0    65.0           130.0         NaN              Aetna
2          103  34.5    80.0           129.0         NaN              Cigna
3          104  45.0    74.0           140.0         NaN       UnitedHealth
4          105  29.0    75.0           125.0         NaN                NaN
5          106  34.5    74.0           129.0         NaN         Blue Cross
6          107  38.0    68.0           135.0         NaN              Aetna
7          108  52.0    90.0           129.0         NaN              Cigna
8          109  27.0    72.0           118.0         NaN       UnitedHealth
9          110  41.0    85.0           145.0         NaN         Blue Cross
10         111  33.0    78.0           128.0         NaN              Aetna
11         112  34.5    74.0           129.0         NaN                NaN
12         1

/tmp/ipykernel_1039/334326224.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['blood_pressure'].fillna(df['blood_pressure'].median(), inplace=True)


It first calculates the median of the existing 'blood_pressure' values. Then, it uses this median to fill in any NaN (missing) values in that column.

In [44]:
df['medication'] = pd.to_numeric(df['medication'], errors='coerce')
df['medication'] = df['medication'].fillna(df['medication'].median())
df['medication'].fillna(df['medication'].mode()[0], inplace=True)
print(df)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0        74.0         Blue Cross
1          102  34.0    65.0           130.0        74.0              Aetna
2          103  34.5    80.0           129.0        74.0              Cigna
3          104  45.0    74.0           140.0        74.0       UnitedHealth
4          105  29.0    75.0           125.0        74.0                NaN
5          106  34.5    74.0           129.0        74.0         Blue Cross
6          107  38.0    68.0           135.0        74.0              Aetna
7          108  52.0    90.0           129.0        74.0              Cigna
8          109  27.0    72.0           118.0        74.0       UnitedHealth
9          110  41.0    85.0           145.0        74.0         Blue Cross
10         111  33.0    78.0           128.0        74.0              Aetna
11         112  34.5    74.0           129.0        74.0                NaN
12         1

/tmp/ipykernel_1039/3160891071.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['medication'].fillna(df['medication'].mode()[0], inplace=True)


handles missing values in the 'medication' column. It first calculates the mode, which is the most frequently occurring value, from the 'medication' column using df['medication'].mode()[0].

In [46]:
df['insurance_provider'] = pd.to_numeric(df['insurance_provider'], errors='coerce')
df['insurance_provider'] = df['insurance_provider'].fillna(df['weight'].median())
df['insurance_provider'].fillna(df['insurance_provider'].mode()[0], inplace=True)
#df['insurance_provider'] = df['insurance_provider'].cat.add_categories('Unknown')
df['insurance_provider'].fillna('Unknown', inplace=True)
print(df)

    patient_id   age  weight  blood_pressure  medication  insurance_provider
0          101  25.0    70.0           120.0        74.0                74.0
1          102  34.0    65.0           130.0        74.0                74.0
2          103  34.5    80.0           129.0        74.0                74.0
3          104  45.0    74.0           140.0        74.0                74.0
4          105  29.0    75.0           125.0        74.0                74.0
5          106  34.5    74.0           129.0        74.0                74.0
6          107  38.0    68.0           135.0        74.0                74.0
7          108  52.0    90.0           129.0        74.0                74.0
8          109  27.0    72.0           118.0        74.0                74.0
9          110  41.0    85.0           145.0        74.0                74.0
10         111  33.0    78.0           128.0        74.0                74.0
11         112  34.5    74.0           129.0        74.0                74.0

/tmp/ipykernel_1039/2780427525.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['insurance_provider'].fillna(df['insurance_provider'].mode()[0], inplace=True)
/tmp/ipykernel_1039/2780427525.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].m

 attempts to handle missing values in the 'insurance_provider' column by filling them with the string 'Unknown'. explicitly adds 'Unknown' as a new valid category to the 'insurance_provider' column.

In [47]:
df.isnull().sum()
print(df)



    patient_id   age  weight  blood_pressure  medication  insurance_provider
0          101  25.0    70.0           120.0        74.0                74.0
1          102  34.0    65.0           130.0        74.0                74.0
2          103  34.5    80.0           129.0        74.0                74.0
3          104  45.0    74.0           140.0        74.0                74.0
4          105  29.0    75.0           125.0        74.0                74.0
5          106  34.5    74.0           129.0        74.0                74.0
6          107  38.0    68.0           135.0        74.0                74.0
7          108  52.0    90.0           129.0        74.0                74.0
8          109  27.0    72.0           118.0        74.0                74.0
9          110  41.0    85.0           145.0        74.0                74.0
10         111  33.0    78.0           128.0        74.0                74.0
11         112  34.5    74.0           129.0        74.0                74.0

calculates and displays the total number of missing (null) values in each column of your DataFrame df. Since all missing values were handled in the previous steps, this output now shows 0 for every column, indicating that there are no remaining missing values.

In [48]:
#task 4:handle duplicates
print(df[df.duplicated(keep=False)])


    patient_id   age  weight  blood_pressure  medication  insurance_provider
0          101  25.0    70.0           120.0        74.0                74.0
6          107  38.0    68.0           135.0        74.0                74.0
15         101  25.0    70.0           120.0        74.0                74.0
16         107  38.0    68.0           135.0        74.0                74.0


In [ ]:
# Missing values after conversion
missing_after = df[['age', 'weight']].isnull().sum()

# Newly created missing values
#new_missing = missing_after - missing_before

#print("Missing Before:\n", missing_before)
print("\nMissing After:\n", missing_after)
print("\nNew Missing Created:\n", new_missing)

NameError: name 'df' is not defined

In [ ]:
df['insurance_provider'] = df['insurance_provider'].astype('category')

df.dtypes

,0
patient_id,int64
age,float64
weight,float64
blood_pressure,float64
medication,object
insurance_provider,category


In [ ]:
df['age'].fillna(df['age'].median(), inplace=True)
print(df)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0             NaN  Lisinopril              Cigna
3          104  45.0     NaN           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106  34.5     NaN             NaN   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0             NaN     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5     NaN             NaN     Aspirin                NaN
12         1

/tmp/ipykernel_1319/3961273402.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)


In [ ]:
df['weight']=fillna(df['weight'].median(), inplace=True)
print(df)

NameError: name 'fillna' is not defined

In [ ]:
df['blood_pressure'].fillna(df['blood_pressure'].median(), inplace=True)
print(df)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0           129.0  Lisinopril              Cigna
3          104  45.0    74.0           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106  34.5    74.0           129.0   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0           129.0     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5    74.0           129.0     Aspirin                NaN
12         1

/tmp/ipykernel_1319/3436943839.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['blood_pressure'].fillna(df['blood_pressure'].median(), inplace=True)


In [ ]:
df['medication'].fillna(df['medication'].mode()[0], inplace=True)
print(df)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0           129.0  Lisinopril              Cigna
3          104  45.0    74.0           140.0     Aspirin       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106  34.5    74.0           129.0   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0           129.0     Aspirin              Cigna
8          109  27.0    72.0           118.0     Aspirin       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5    74.0           129.0     Aspirin                NaN
12         1

/tmp/ipykernel_1319/2192569817.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['medication'].fillna(df['medication'].mode()[0], inplace=True)


In [49]:
df.isnull().sum()
print(df)

    patient_id   age  weight  blood_pressure  medication  insurance_provider
0          101  25.0    70.0           120.0        74.0                74.0
1          102  34.0    65.0           130.0        74.0                74.0
2          103  34.5    80.0           129.0        74.0                74.0
3          104  45.0    74.0           140.0        74.0                74.0
4          105  29.0    75.0           125.0        74.0                74.0
5          106  34.5    74.0           129.0        74.0                74.0
6          107  38.0    68.0           135.0        74.0                74.0
7          108  52.0    90.0           129.0        74.0                74.0
8          109  27.0    72.0           118.0        74.0                74.0
9          110  41.0    85.0           145.0        74.0                74.0
10         111  33.0    78.0           128.0        74.0                74.0
11         112  34.5    74.0           129.0        74.0                74.0

print(df[df.duplicated(keep=False)]) is used to identify and display all duplicate rows in your DataFrame df.

In [50]:
print(df[df.duplicated(keep=False)])
print(df[df.duplicated(subset=['patient_id'])])
print("Shape before removing duplicates:", df.shape)
print("Shape before removing duplicates:", df.shape)
print("Shape after removing duplicates:", df.shape)
rows_removed = 20 - df.shape[0]
print("Rows removed:", rows_removed)

    patient_id   age  weight  blood_pressure  medication  insurance_provider
0          101  25.0    70.0           120.0        74.0                74.0
6          107  38.0    68.0           135.0        74.0                74.0
15         101  25.0    70.0           120.0        74.0                74.0
16         107  38.0    68.0           135.0        74.0                74.0
    patient_id   age  weight  blood_pressure  medication  insurance_provider
15         101  25.0    70.0           120.0        74.0                74.0
16         107  38.0    68.0           135.0        74.0                74.0
Shape before removing duplicates: (20, 6)
Shape before removing duplicates: (20, 6)
Shape after removing duplicates: (20, 6)
Rows removed: 0


print(df[df.duplicated(keep=False)]), displays all rows that are exact duplicates, marking every instance of a duplicate as such. The second line, print(df[df.duplicated(subset=['patient_id'])]), specifically shows rows where only the 'patient_id' is duplicated. Following this, it prints the current shape of the DataFrame multiple times, which currently reflects the state before any duplicates are actually removed. Finally, it calculates rows_removed by comparing the initial expected row count (20) with the current DataFrame's row count.
Please explain this code:

Certainly! This comprehensive code block starts by recreating your DataFrame df with the initial patient data. It then proceeds to clean and preprocess several columns:

    

In [52]:
#task 5:create a copy
import pandas as pd
import numpy as np

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)
df_clean = df.copy()
print("===== BEFORE CLEANING =====")

print("Shape:", df_clean.shape)

print("\nMissing Values:")
print(df_clean.isnull().sum())

print("\nDuplicate Rows:")
print(df_clean.duplicated(subset=['patient_id']).sum())

print("\nData Types:")
print(df_clean.dtypes)
df_clean['age'] = pd.to_numeric(df_clean['age'], errors='coerce')
df_clean['weight'] = pd.to_numeric(df_clean['weight'], errors='coerce')

df_clean['medication'] = df_clean['medication'].fillna(
    df_clean['medication'].mode()[0]
)

df_clean['insurance_provider'] = df_clean['insurance_provider'].fillna("Unknown")
df_clean['insurance_provider'] = df_clean['insurance_provider'].astype('category')
df_clean = df_clean.drop_duplicates(subset=['patient_id'], keep='first')
print("\n===== AFTER CLEANING =====")

print("Shape:", df_clean.shape)

print("\nMissing Values:")
print(df_clean.isnull().sum())

print("\nDuplicate Rows:")
print(df_clean.duplicated(subset=['patient_id']).sum())

print("\nData Types:")
print(df_clean.dtypes)

===== BEFORE CLEANING =====
Shape: (20, 6)

Missing Values:
patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

Duplicate Rows:
2

Data Types:
patient_id              int64
age                    object
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

===== AFTER CLEANING =====
Shape: (18, 6)

Missing Values:
patient_id            0
age                   4
weight                5
blood_pressure        6
medication            0
insurance_provider    0
dtype: int64

Duplicate Rows:
0

Data Types:
patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object



After all manipulations: Result:
Start fresh: reload the DataFrame and create a copy using df_clean = df.copy()
Perform ALL cleaning steps in order: types → missing values → duplicates
Create a verification report showing:

    Shape before and after
    Missing values before and after
    Duplicates before and after
    Data types before and after


