# -*- coding: utf-8 -*-
"""inventory.json

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tgu3l1xuLrDZfSzr3Ccs8RbfOm9asgp2
"""

import json

inventory = [
{"title": "The Alchemist", "author": "Paulo Coelho", "price": 12.99, "in_stock": True},
{"title": "1984", "author": "George Orwell", "price": 9.99, "in_stock": True},
]

with open("inventory.json", "w") as file:
	json.dump(inventory, file, indent=4)

print("inventory.json file created successfully!")
import json

# Open and read the inventory file
with open("inventory.json", "r") as file:
	 inventory = json.load(file)

# Print total number of books
print("Total number of books:", len(inventory))

import json

# New book to add
new_book = {
  "title": "Atomic Habits",
   "author": "James Clear",
   "price": 14.99,
  "in_stock": True
}
# Step 1: Read existing inventory
with open("inventory.json", "r") as file:
     inventory = json.load(file)

# Step 2: Append new book
     inventory.append(new_book)

# Step 3: Write updated inventory back to file
with open("inventory.json", "w") as file:
     json.dump(inventory, file, indent=4)

print("New book added successfully!")
print("Inventory updated and saved successfully!")

with open("inventory.json", "r") as file:
   inventory = json.load(file)

seen_titles = set()

for book in inventory:
 if book["title"] not in seen_titles:
    print(f"Title: {book['title']} | Author: {book['author']} | Price: ${book['price']:.2f}")
    seen_titles.add(book["title"])